### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows

### ISSUE THREAD

**Issue by JWEi1994** [yyueniao/miters#26]
### Description
I was getting the following errors when I run `npm run live`.

### Debug Logs
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at defer (D:\Discord\miters\node_modules\ts-node\src\esm.ts:159:23)
    at entrypointFallback (D:\Discord\miters\node_modules\ts-node\src\esm.ts:168:34)
    at D:\Discord\miters\node_modules\ts-node\src\esm.ts:202:16
    at addShortCircuitFlag (D:\Discord\miters\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (D:\Discord\miters\node_modules\ts-node\src\esm.ts:197:12)
    at resolve (D:\Discord\miters\node_modules\ts-node\src\child\child-loader.ts:15:39) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

### **Environment**
- OS: Windows 11
- Node.js: 18.14.0

**Comment by pwkang** [comment]
Created a PR (#27) to solve this issue
